language: ruby
rvm:
  - "1.9.3"
  - "2.0.0"
  - "2.1.1"
  - ruby-head
script: rake spec
install: gem install hen rspec curb nokogiri
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libcurl4-openssl-dev
